Repository pulp/pulp_python, pull requests merged in 2018-05, with the labels that each got.

#151 Added functional tests
  .gitignore
  .travis.yml
  .travis/before_script.sh
  .travis/script.sh
  pulp_python/tests/functional/__init__.py
  pulp_python/tests/functional/api_v3/__init__.py
  pulp_python/tests/functional/api_v3/test_crd_publications.py
  pulp_python/tests/functional/api_v3/test_crud_publishers.py
  pulp_python/tests/functional/api_v3/test_crud_remotes.py
  pulp_python/tests/functional/api_v3/test_download_content.py
  pulp_python/tests/functional/api_v3/test_orphans.py
  pulp_python/tests/functional/api_v3/test_publish.py
  pulp_python/tests/functional/api_v3/test_repo_version.py
  pulp_python/tests/functional/api_v3/test_sync.py
  pulp_python/tests/functional/api_v3/test_unlinking_repo.py
  pulp_python/tests/functional/constants.py
  pulp_python/tests/functional/utils.py
  pulp_python/tests/unit/__init__.py
  pulp_python/tests/unit/test_models.py
Labels: 3.0

#153 Add sync and publish serializers
  pulp_python/app/serializers.py
  pulp_python/app/viewsets.py
Labels: 3.0

#160 Mirror some changes to pulp-file smash tests
  pulp_python/tests/functional/api_v3/test_crd_publications.py
  pulp_python/tests/functional/api_v3/test_crud_remotes.py
  pulp_python/tests/functional/api_v3/test_download_content.py
  pulp_python/tests/functional/api_v3/test_orphans.py
  pulp_python/tests/functional/api_v3/test_publish.py
  pulp_python/tests/functional/api_v3/test_repo_version.py
  pulp_python/tests/functional/api_v3/test_sync.py
  pulp_python/tests/functional/api_v3/test_unlinking_repo.py
  pulp_python/tests/functional/utils.py
Labels: 3.0

#161 Add basic filters to pulp_python
  pulp_python/app/viewsets.py
Labels: 3.0

#162 Keywords string serialized to Char not List
  pulp_python/app/serializers.py
  pulp_python/app/utils.py
Labels: 3.0

#158 Docs reorganization
  README.rst
  docs/admin-docs/configuration.rst
  docs/admin-docs/index.rst
  docs/admin-docs/installation.rst
  docs/index.rst
  docs/installation.rst
  docs/reference/index.rst
  docs/reference/python-type.rst
  docs/reference/remote.rst
  docs/release-notes/1.0.rst
  docs/release-notes/1.1.rst
  docs/release-notes/2.0.rst
  docs/release-notes/index.rst
  docs/user-docs/getting_started.rst
  docs/user-docs/index.rst
  docs/workflows/index.rst
  docs/workflows/publish-host.rst
  docs/workflows/sync.rst
  docs/workflows/upload.rst
Labels: 3.0, Documentation, Work In Progress

#164 Prepare setup.py for release
  MANIFEST.in
  pulp_python/tests/functional/api_v3/test_orphans.py
  pulp_python/tests/functional/api_v3/test_publish.py
  pulp_python/tests/functional/api_v3/test_repo_version.py
  setup.py
Labels: 3.0

#166 Minor changes to install docs
  docs/installation.rst
Labels: 3.0, Documentation

#165 Copy over auto distribution test from pulp-smash
  pulp_python/tests/functional/api/__init__.py
  pulp_python/tests/functional/api/test_auto_distribution.py
  pulp_python/tests/functional/api/test_crd_publications.py
  pulp_python/tests/functional/api/test_crud_publishers.py
  pulp_python/tests/functional/api/test_crud_remotes.py
  pulp_python/tests/functional/api/test_download_content.py
  pulp_python/tests/functional/api/test_orphans.py
  pulp_python/tests/functional/api/test_publish.py
  pulp_python/tests/functional/api/test_repo_version.py
  pulp_python/tests/functional/api/test_sync.py
  pulp_python/tests/functional/api/test_unlinking_repo.py
Labels: 3.0

#169 Update imports to account for namespace changes
  pulp_python/tests/functional/api/test_auto_distribution.py
  pulp_python/tests/functional/api/test_crd_publications.py
  pulp_python/tests/functional/api/test_crud_publishers.py
  pulp_python/tests/functional/api/test_crud_remotes.py
  pulp_python/tests/functional/api/test_download_content.py
  pulp_python/tests/functional/api/test_orphans.py
  pulp_python/tests/functional/api/test_publish.py
  pulp_python/tests/functional/api/test_repo_version.py
  pulp_python/tests/functional/api/test_sync.py
  pulp_python/tests/functional/api/test_unlinking_repo.py
Labels: 3.0

#170 Mirror Pulp Smash changes
  docs/installation.rst
  pulp_python/tests/functional/api/test_auto_distribution.py
  pulp_python/tests/functional/api/test_repo_version.py
  pulp_python/tests/functional/utils.py
Labels: 3.0

#172 Update auto-distribution tests from pulp-smash
  .travis/script.sh
  pulp_python/tests/functional/api/test_auto_distribution.py
  pulp_python/tests/functional/utils.py
Labels: 3.0

#171 Added a "keyword" filter
  pulp_python/app/viewsets.py
Labels: 3.0, enhancement

#176 Consolidate pulp-smash status checks
  pulp_python/tests/functional/api/test_crd_publications.py
  pulp_python/tests/functional/api/test_download_content.py
  pulp_python/tests/functional/api/test_repo_version.py
  pulp_python/tests/functional/api/test_unlinking_repo.py
Labels: 3.0
