Repository pulp/pulp_python, pull requests merged in 2018-06, with the labels that each got.

#173 As a user, I can whitelist packages to sync with standard python syntax
  .travis/install.sh
  docs/installation.rst
  docs/workflows/sync.rst
  pulp_python/app/models.py
  pulp_python/app/serializers.py
  pulp_python/app/tasks/sync.py
  pulp_python/app/viewsets.py
  pulp_python/tests/functional/constants.py
  setup.py
Labels: 3.0, enhancement

#181 Bump version to beta3, add release notes
  docs/index.rst
  docs/release-notes/3.0.z.rst
  setup.py
Labels: 3.0

#182 Update w/ Pulp Smash changes and fix bug
  pulp_python/app/serializers.py
  pulp_python/tests/functional/api/test_crud_remotes.py
  pulp_python/tests/functional/utils.py
Labels: 3.0

#183 normalize project name before publish
  .pep8speaks.yml
  plugins/pulp_python/plugins/distributors/steps.py
  plugins/pulp_python/plugins/utils.py
  plugins/test/unit/plugins/distributors/test_steps.py
Labels: bug

#184 Smash framework changes
  pulp_python/tests/functional/api/test_auto_distribution.py
  pulp_python/tests/functional/api/test_crd_publications.py
  pulp_python/tests/functional/api/test_crud_content_unit.py
  pulp_python/tests/functional/api/test_crud_publishers.py
  pulp_python/tests/functional/api/test_download_content.py
  pulp_python/tests/functional/api/test_orphans.py
  pulp_python/tests/functional/api/test_publish.py
  pulp_python/tests/functional/api/test_repo_version.py
  pulp_python/tests/functional/api/test_sync.py
  pulp_python/tests/functional/api/test_unlinking_repo.py
  pulp_python/tests/functional/constants.py
  pulp_python/tests/functional/utils.py
Labels: 3.0

#185 Update viewsets to use url serializers from core
  pulp_python/app/serializers.py
  pulp_python/app/viewsets.py
Labels: 3.0
